// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC40mPFETvphi-_K0bkwPDeZ7bFu01EJzM',
    appId: '1:1020899138518:web:8b973c1b50714f0a206277',
    messagingSenderId: '1020899138518',
    projectId: 'myhealthapp-505c5',
    authDomain: 'myhealthapp-505c5.firebaseapp.com',
    storageBucket: 'myhealthapp-505c5.firebasestorage.app',
    measurementId: 'G-REVL3H49JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ7m2xjnwetfBpzD0HNQOqW6ik34QevIQ',
    appId: '1:1020899138518:android:6ddba33602057431206277',
    messagingSenderId: '1020899138518',
    projectId: 'myhealthapp-505c5',
    storageBucket: 'myhealthapp-505c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHfrRciBy6eZoEVBsvKEjzWv8pFsCVO8Q',
    appId: '1:1020899138518:ios:c9c5940d929e542f206277',
    messagingSenderId: '1020899138518',
    projectId: 'myhealthapp-505c5',
    storageBucket: 'myhealthapp-505c5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHfrRciBy6eZoEVBsvKEjzWv8pFsCVO8Q',
    appId: '1:1020899138518:ios:c9c5940d929e542f206277',
    messagingSenderId: '1020899138518',
    projectId: 'myhealthapp-505c5',
    storageBucket: 'myhealthapp-505c5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC40mPFETvphi-_K0bkwPDeZ7bFu01EJzM',
    appId: '1:1020899138518:web:aed97e0b33f522fe206277',
    messagingSenderId: '1020899138518',
    projectId: 'myhealthapp-505c5',
    authDomain: 'myhealthapp-505c5.firebaseapp.com',
    storageBucket: 'myhealthapp-505c5.firebasestorage.app',
    measurementId: 'G-MMBX4HLPFZ',
  );
}
